Description: Auth - Registration
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  dockerTag:
    Type: String
    Description: Docker tag to deploy
  wwwRoot:
    Type: String
    Description: WWW root for calling API
  environmentSuffix:
    Type: String
    AllowedValues:
      - ''
      - -int
      - -sys
    Description: Environment suffix e.g -int -sys
  TestClusterName:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Name of test cluster
    Default: TestClusterName
  ProductionClusterName:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Name of production cluster
    Default: ProductionClusterName

Conditions:
  isTesting: !Or
    - !Equals [!Ref environmentSuffix, "-int"]
    - !Equals [!Ref environmentSuffix, "-sys"]

Resources:
  taskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      ContainerDefinitions:
        - Name: auth-registration
          Cpu: '1'
          Essential: 'true'
          Image: !Sub 'docker.io/linn/auth-registration:${dockerTag}'
          PortMappings:
            - ContainerPort: 3000
          Memory: '150'
          LogConfiguration:
            LogDriver: gelf
            Options:
              gelf-address: 'udp://syslog.linn.co.uk:12201'
              tag: !Sub 'auth-registration-${dockerTag}-ecs-task'
          Environment:
            - Name: WWW_ROOT
              Value: !Ref wwwRoot
            - Name: awsRegion
              Value: !Ref 'AWS::Region'
  service:
    Type: 'AWS::ECS::Service'
    Properties:
      # Have to use long form conditional
      Cluster: !If
        - isTesting
        - !Sub ${TestClusterName}
        - !Sub ${ProductionClusterName}
      DesiredCount: !If [ isTesting, 1, 2]
      TaskDefinition: !Ref taskDefinition
      Role: ecsServiceRole
      LoadBalancers:
        - ContainerName: auth-registration
          ContainerPort: 3000
          TargetGroupArn: !ImportValue
            'Fn::Sub': 'authRegistrationTargetGroupArn${environmentSuffix}'
