Description: Auth - Registration
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  targetCluster:
    Type: String
    Description: ECS Cluster name within which this application should be run
  dockerTag:
    Type: String
    Description: Docker tag to deploy
  wwwRoot:
    Type: String
    Description: WWW root for calling API
  desiredCount:
    Type: String
    Description: Desired number of instances
  environmentSuffix:
    Type: String
    Description: Environment suffix e.g -int -sys
Resources:
  taskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      ContainerDefinitions:
        - Name: auth-registration
          Cpu: '1'
          Essential: 'true'
          Image: !Sub 'docker.io/linn/auth-registration:${dockerTag}'
          PortMappings:
            - ContainerPort: 3000
          Memory: '150'
          LogConfiguration:
            LogDriver: gelf
            Options:
              gelf-address: 'udp://syslog.linn.co.uk:12201'
              tag: !Sub 'auth-registration-${dockerTag}-ecs-task'
          Environment:
            - Name: WWW_ROOT
              Value: !Ref wwwRoot
            - Name: awsRegion
              Value: !Ref 'AWS::Region'
  service:
    Type: 'AWS::ECS::Service'
    Properties:
      Cluster: !Ref targetCluster
      DesiredCount: !Ref desiredCount
      TaskDefinition: !Ref taskDefinition
      Role: ecsServiceRole
      LoadBalancers:
        - ContainerName: auth-registration
          ContainerPort: 3000
          TargetGroupArn: !ImportValue 
            'Fn::Sub': 'authRegistrationTargetGroupArn${environmentSuffix}'
